version: 1.0
provider:
  name: openfaas
  gateway: https://VEBA_FQDN_OR_IP
functions:
  pre-filter:
    lang: python3-flask
    handler: ./pre-filter
    image: vmware/veba-python-pre-filter:latest
    environment:
      write_debug: true
      read_debug: true
      insecure_ssl: false # set to true to disable validation of vcenter ssl certificate
      match_all: false # require that all filters be positively matched to event data
      call_function: veba-echo # chained function to call
      filter_vm: '.*'
    secrets:
      - vcconfig
    annotations:
      topic: "DrsVmPoweredOnEvent,VmPoweredOnEvent"
