builder_host = "192.168.30.5"
builder_host_username = "root"
builder_host_password = "VMware1!"
builder_host_datastore = "sm-vsanDatastore"
builder_host_portgroup = "VM Network"
ovftool_deploy_vcenter = "192.168.30.3"
ovftool_deploy_vcenter_username = "administrator@vsphere.local"
ovftool_deploy_vcenter_password = "VMware1!"

vm_name = "VMware_Event_Broker_Appliance"
iso_checksum = "5af288017d0d1198dd6bd02ad40120eb"
iso_url = "https://packages.vmware.com/photon/4.0/Rev2/iso/photon-4.0-c001795b8.iso"
numvcpus = "6"
ramsize = "8192"
guest_username = "root"
guest_password = "##FILL-IN-SECURE-PASSWORD##"
