variable "VEBA_COMMIT" {
  type = string
  description = "VEBA Github Commit ID (auto-generated by build)"
  default = "NULL"
}

variable "VEBA_VERSION" {
  type = string
  description = "VEBA Version (auto-generated by build)"
  default = "NULL"
}

variable "builder_host" {
  type = string
  description = "ESXi Server IP Address or FQDN"
}

variable "builder_host_datastore" {
  type = string
  description = "ESXi Datastore"
}

variable "builder_host_password" {
  type = string
  description = "ESXi root user password"
}

variable "builder_host_portgroup" {
  type = string
  description = "ESXi network portgroup"
}

variable "builder_host_username" {
  type = string
  description = "ESXi username"
}

variable "guest_password" {
  type = string
  description = "Root user password"
}

variable "guest_username" {
  type = string
  description = "Root user username"
  default = "root"
}

variable "iso_checksum" {
  type = string
  description = "MD5 Checksum of the ISO File"
}

variable "iso_url" {
  type = string
  description = "URL to ISO Installer"
}

variable "numvcpus" {
  type = string
  description = "vCPU configuration for VEBA Appliance"
}

variable "ovftool_deploy_vcenter" {
  type    = string
  description = "vCenter Server IP Address or FQDN"
}

variable "ovftool_deploy_vcenter_password" {
  type    = string
  description = "vCenter Server Password"
}

variable "ovftool_deploy_vcenter_username" {
  type    = string
  description = "vCenter Server Username"
}

variable "ramsize" {
  type = string
  description = "Memory (MB) configuration for VEBA appliance"
}

variable "veba_ovf_template" {
  type    = string
  description = "Name of the Photon OVF template file"
  default = "photon.xml.template"
}

variable "vm_name" {
  type = string
  description = "Virtual Machine name for VEBA Appliance"
  default = "VMware_Event_Broker_Appliance"
}