provider:
  name: openfaas
  gateway: https://veba.primp-industries.com
functions:
  powershell-datastore-usage:
    lang: powercli
    handler: ./handler
    image: vmware/veba-powercli-datastore-notification:latest
    environment:
      write_debug: true
      read_debug: true
      function_debug: false
    secrets:
      - vc-datastore-config
    annotations:
      topic: AlarmStatusChangedEvent
