provider:
  name: openfaas
  gateway: https://phxlvveba01.itplab.local
functions:
  nsxttagsync:
    lang: powercli
    handler: ./handler
    image: vmware/veba-powercli-tag-sync-to-nsxt:latest
    environment:
      write_debug: false
      read_debug: false
      function_debug: false
    secrets:
      - nsx-secrets
    annotations:
      topic: com.vmware.cis.tagging.attach,com.vmware.cis.tagging.detach
