provider:
  name: openfaas
  gateway: https://VEBA_FQDN_OR_IP
functions:
  pdinvoke-fn:
    lang: python3
    handler: ./handler
    image: vmware/veba-python-pagerduty:latest
    environment:
      write_debug: true
      read_debug: true
      combine_output: false
      insecure_ssl: true
    secrets:
      - pdconfig
    annotations:
      topic: VmPoweredOnEvent,VmPoweredOffEvent