version: 1.0
provider:
  name: openfaas
  gateway: https://veba.yourdomain.com
functions:
  go-pagerduty-trigger-fn:
    lang: golang-http
    handler: ./handler
    image: vmware/veba-go-pagerduty-trigger:latest
    secrets:
      - pdconfig
    annotations:
      topic: VmReconfiguredEvent
