version: 1.0
provider:
  name: openfaas
  gateway: https://veba.yourdomain.com
functions:
  vm-reconfig-via-tag-fn:
    lang: golang-http
    handler: ./handler
    image: vmware/veba-go-vm-reconfig-via-tag:latest
    environment:
      write_debug: true
    secrets:
      - vcconfig
    annotations:
      topic: VmPoweredOffEvent
