# photon:3.0-20210514
FROM photon@sha256:ec5b5e7bf027963c146ad22e411c18d288fa1bacf847f592603864d00e14c95c
ENV TERM linux-basic
ENV PORT 8080

ARG POWERSHELL_VERSION="7.1.4-1.ph3"
ARG ICU_VERSION="67.1"
ARG CURL_VERSION="7.75.0-2.ph3"
ARG RPM_LIBS="4.14.2-12.ph3"
ARG THREADJOB_VERSION="2.0.3"
ARG CLOUDEVENTS_SDK_VERSION="0.3.3"

# Set terminal. If we don't do this, weird readline things happen.
RUN echo "/usr/bin/pwsh" >> /etc/shells && \
    echo "/bin/pwsh" >> /etc/shells && \
    tdnf install -y powershell-${POWERSHELL_VERSION} icu-${ICU_VERSION} curl-${CURL_VERSION} rpm-libs-${RPM_LIBS} && \
    pwsh -c "Set-PSRepository -Name PSGallery -InstallationPolicy Trusted" && \
    pwsh -c "Install-Module ThreadJob -Force -Confirm:\$false -RequiredVersion ${THREADJOB_VERSION}" && \
    pwsh -c "Install-Module -Name CloudEvents.Sdk -RequiredVersion ${CLOUDEVENTS_SDK_VERSION}" && \
    find / -name "net45" | xargs rm -rf && \
    mkdir -p /root/.config/powershell && \
    echo '$ProgressPreference = "SilentlyContinue"' > /root/.config/powershell/Microsoft.PowerShell_profile.ps1 && \
    tdnf clean all

COPY server.ps1 ./

CMD ["pwsh","./server.ps1"]