# Ubuntu 20.04 base image w/PowerShell 7.2.11
FROM mcr.microsoft.com/powershell:lts-ubuntu-20.04
ENV TERM linux-basic
ENV PORT 8080

ENV TZ=Etc/UTC
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata

ARG THREADJOB_VERSION="2.0.3"
ARG CLOUDEVENTS_SDK_VERSION="0.3.3"

# Set terminal. If we don't do this, weird readline things happen.
RUN echo "/usr/bin/pwsh" >> /etc/shells && \
    echo "/bin/pwsh" >> /etc/shells && \
    pwsh -c "Set-PSRepository -Name PSGallery -InstallationPolicy Trusted" && \
    pwsh -c "Install-Module ThreadJob -Force -Confirm:\$false -RequiredVersion ${THREADJOB_VERSION}" && \
    pwsh -c "Install-Module -Name CloudEvents.Sdk -RequiredVersion ${CLOUDEVENTS_SDK_VERSION}" && \
    find / -name "net45" | xargs rm -rf && \
    mkdir -p /root/.config/powershell && \
    echo '$ProgressPreference = "SilentlyContinue"' > /root/.config/powershell/Microsoft.PowerShell_profile.ps1 && \
    apt-get clean

COPY server.ps1 ./

CMD ["pwsh","./server.ps1"]