apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kn-ps-webhook
  labels:
    app: veba-ui
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "1"
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: us.gcr.io/daisy-284300/veba/kn-ps-webhook:1.1
          envFrom:
            - secretRef:
                name: webhook-secret
          env:
            - name: SERVICE_DEBUG
              value: "false"