toc:
  - title: Introduction
    subfolderitems:
      - page: Use Cases
        id: intro-about
        url: /kb/
      - page: Architecture
        id: intro-architecture
        url: /kb/architecture
      - page: VMware Event Router
        id: intro-event-router
        url: /kb/event-router
      - page: Functions
        id: intro-functions
        url: /kb/functions

  - title: Install
    subfolderitems:
      - page: VEBA (Knative)
        id: install-knative
        url: /kb/install-knative

  - title: Use
    subfolderitems:
      - page: vCenter Events
        id: use-vcenter-events
        url: /kb/vcenter-events
      - page: Horizon Events
        id: use-horizon-events
        url: /kb/horizon-events
      - page: Event Specification
        id: use-eventspec
        url: /kb/eventspec
      - page: Deploy Functions
        id: use-functions
        url: /kb/use-functions

  - title: Contribute
    subfolderitems:
      - page: Getting Started
        id: contribute-start
        url: /kb/contribute-start
      - page: Build Functions
        id: contribute-functions
        url: /kb/contribute-functions
      - page: Build Event Router
        id: contribute-eventrouter
        url: /kb/contribute-eventrouter
      - page: Build Appliance
        id: contribute-appliance
        url: /kb/contribute-appliance
      - page: Build Website
        id: contribute-site
        url: /kb/contribute-site

  - title: Advanced
    subfolderitems:
      - page: Deploy VEBA to Kubernetes
        id: advanced-deploy-k8s
        url: /kb/event-router#deployment
      - page: Deploy Event Router to Kind
        id: site-resources
        url: /kb/deploy-event-router-kind
      - page: In-depth Function Tutorial
        id: function-tutorial-intro
        url: /kb/function-tutorial-intro
      - page: Replace TLS Certificates on VEBA
        id: advanced-certificates
        url: /kb/advanced-certificates
      - page: Using Private Container Registry with VEBA
        id: private-registry
        url: /kb/private-registry
      - page: Monitoring VEBA with vROps
        id: site-resources
        external_url: https://rguske.github.io/post/monitoring-the-vmware-event-broker-appliance-with-vrealize-operations-manager/

  - title: Troubleshoot
    subfolderitems:
      - page: Troubleshooting Appliance
        id: troubleshoot-appliance
        url: /kb/troubleshoot-appliance
      - page: Troubleshooting Functions
        id: troubleshoot-functions
        url: /kb/troubleshoot-functions

  - title: More..
    subfolderitems:
      - page: FAQ
        id: site-faq
        url: /faq
      - page: Resources
        id: site-resources
        url: /resources
