provider:
  name: openfaas
  gateway: https://veba.primp-industries.com
functions:
  powercli-reconfigure:
    lang: powercli
    handler: ./handler
    image: vmware/veba-powercli-vm-config-change-slack:latest
    environment:
      write_debug: true
      read_debug: true
      function_debug: false
    secrets:
      - vc-slack-config
    annotations:
      topic: VmReconfiguredEvent
