apiVersion: v1
kind: Secret
metadata:
  name: {{ include "router.name" . }}-{{ .Values.eventrouter.config.name }}
  labels:
{{ include "router.labels" . | indent 4 }}
type: Opaque
data:
  {{ .Values.eventrouter.config.fileName }}: {{ tpl (.Files.Get "config.yaml") . | b64enc }}
