provider:
  name: openfaas
  gateway: https://VEBA_FQDN_OR_IP
functions:
  pytag-fn:
    lang: python3
    handler: ./handler
    image: embano1/pytag-fn:0.2
    environment:
      write_debug: true
      read_debug: true
    secrets:
      - vcconfig
    annotations:
      topic: vm.powered.on