apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kn-py-cbc-deploy-sensor
  labels:
    app: veba-ui
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "1"
        autoscaling.knative.dev/minScale: "0"
    spec:
      containers:
        - image: us.gcr.io/daisy-284300/veba/kn-py-cbc-deploy-sensor:1.0
          envFrom:
            - secretRef:
                name: cbc-env
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: kn-py-cbc-deploy-sensor-trigger
  labels:
    app: veba-ui
spec:
  broker: default
  filter:
    attributes:
      type: com.vmware.event.router/event
      subject: VmDeployedEvent 
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: kn-py-cbc-deploy-sensor