provider:
  name: openfaas
  gateway: https://veba.primp-industries.com
functions:
  powercli-tag:
    lang: powercli
    handler: ./handler
    image: vmware/veba-powercli-tagging:latest
    environment:
      write_debug: true
      read_debug: true
      function_debug: false
    secrets:
      - vc-tag-config
    annotations:
      topic: DrsVmPoweredOnEvent
