provider:
  name: openfaas
  gateway: https://veba.primp-industries.com
functions:
  powershell-eventbridge:
    lang: powercli
    handler: ./handler
    image: lamw/powershell-eventbridge:latest
    environment:
      write_debug: true
      read_debug: true
      function_debug: false
    secrets:
      - eventbridge-secrets
    annotations:
      topic: vm.removed
