apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kn-pcli-nsx-tag-sync
  labels:
    app: veba-ui
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "1"
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: ghcr.io/vmware-samples/vcenter-event-broker-appliance/kn-pcli-nsx-tag-sync:1.3
          envFrom:
            - secretRef:
                name: tag-secret
          env:
            - name: FUNCTION_DEBUG
              value: "false"
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: veba-pcli-nsx-tag-sync-trigger-attach
  labels:
    app: veba-ui
spec:
  broker: default
  filter:
    attributes:
      subject: com.vmware.vsphere.com.vmware.cis.tagging.attach.v0
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: kn-pcli-nsx-tag-sync
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: veba-pcli-nsx-tag-sync-trigger-detach
  labels:
    app: veba-ui
spec:
  broker: default
  filter:
    attributes:
      subject: com.vmware.vsphere.com.vmware.cis.tagging.detach.v0
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: kn-pcli-nsx-tag-sync
