version: 1.0
provider:
  name: openfaas
  gateway: https://veba.primp-industries.com
functions:
  powercli-entermaint:
    lang: powercli
    handler: ./handler
    image: vmware/veba-powercli-esx-maintenance:latest
    environment:
      write_debug: true
      read_debug: true
      function_debug: false
    secrets:
      - vc-hostmaint-config
    annotations:
      topic: EnteredMaintenanceModeEvent, ExitMaintenanceModeEvent