apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kn-pcli-telegram
  labels:
    app: veba-ui
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "1"
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: us.gcr.io/daisy-284300/veba/kn-pcli-telegram:1.2
          envFrom:
            - secretRef:
                name: telegram-secret
          env:
            - name: FUNCTION_DEBUG
              value: "false"
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: veba-pcli-telegram-trigger
  labels:
    app: veba-ui
spec:
  broker: default
  filter:
    attributes:
      subject: VmMigratedEvent
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: kn-pcli-telegram
