version: 1.0
provider:
  name: openfaas
  gateway: https://veba.yourdomain.com
functions:
  esx-mtu-fixer:
    lang: python
    handler: ./esx-mtu-fixer
    image: vmware/veba-python-esx-mtu:latest
    annotations:
      topic: VmPoweredOnEvent
    environment:
      write_debug: true
      read_debug: true
    secrets:
      - vc-credentials