version: 1.0
provider:
  name: openfaas
  gateway: http://veba.primp-industries.com
functions:
  veba-echo:
    lang: python3-http
    handler: ./echo
    image: vmware/veba-python-echo:latest
    environment:
      write_debug: true
      read_debug: true
    annotations:
      topic: "DrsVmPoweredOnEvent,VmPoweredOnEvent,VmPoweredOffEvent"