name: Release Notes

on:
  push:
    tags:
      - "v*"

jobs:
  changelog:
    name: Create CHANGELOG PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # for changelog
          fetch-depth: 0
          ref: master

      - name: Create CHANGELOG commit
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          IMAGE: quay.io/git-chglog/git-chglog
          # https://quay.io/repository/git-chglog/git-chglog from tag v0.14.2
          IMAGE_SHA: 998e89dab8dd8284cfff5f8cfb9e9af41fe3fcd4671f2e86a180e453c20959e3
        run: |
          # update CHANGELOG
          docker run --rm -v $PWD:/workdir ${IMAGE}@sha256:${IMAGE_SHA} -o CHANGELOG.md
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          git add CHANGELOG.md
          git commit -s -m "Update CHANGELOG for $(basename ${{ github.ref }})"

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          delete-branch: true
          title: "Update CHANGELOG"
          reviewers: embano1
          body: |
            Update CHANGELOG.md for new release

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"