provider:
  name: openfaas
  gateway: https://veba.primp-industries.com
functions:
  powershell-ngw-teams:
    lang: powercli
    handler: ./handler
    image: vmware/veba-powershell-ngw-teams:latest
    environment:
      write_debug: true
      read_debug: true
      function_debug: false
    secrets:
      - ngw-teams-config